In [1]:
#🟢네이버 블로그, 쇼핑 제목으로 트랜드 파악 //search/**	검색API
# 둘 다 실행시"sort":"asc"를 빼거나 맞춰서 "sim"으로 바꾸기
import requests
import pandas as pd

# 1. 네이버 개발자 센터에서 발급받은 '도장' 준비
client_id = "FO94sqAIv4XrxJoV7qSf"
client_secret = "jfkOOP5NuM"

def get_naver_search(category, query, display=100): #함수 선언
    url = f"https://openapi.naver.com/v1/search/{category}.json"
    headers = {
        "X-Naver-Client-Id": client_id,
        "X-Naver-Client-Secret": client_secret
    }
    # "sort":"🔴asc"오름차순(최저가순) / 🔴sim 유사도순 (블로그)
    params = {"query": query, "display": display, "sort":"asc"}
    
    response = requests.get(url, headers=headers, params=params)
    return pd.DataFrame(response.json()['items'])

# 1️⃣🍋블로그 검색: 우리 공사 관련 최신 여론 확인
# df_blog = get_naver_search("blog", "한국전력 에너지절약") #함수 사용
# print("--- 블로그 검색 결과 ---")
# print(df_blog[['title', 'link']].head())

# 2️⃣🍋쇼핑 검색: 관련 물품 최저가 동향 (자산 구입 시 참고)
df_shop = get_naver_search("shop", "사무용 모니터")
# df_shop
print("\n--- 쇼핑 검색 결과 ---")
print(df_shop[['title', 'lprice', 'mallName']].head()) #여러개 부를 때 [[],[],[]]

# 🛑4️⃣데이터 정제부분 //다른 파일로 2-4-3naverAPI으로
df_shop['title'] = df_shop['title'].str.replace('<b>', '', regex=False)
df_shop['title'] = df_shop['title'].str.replace('</b>', '', regex=False)
df_shop['lprice'] = pd.to_numeric(df_shop['lprice']) # 가격을 숫자형으로 변환
df_shop

# 3️⃣수집한 데이터를 엑셀로 저장 -100개
# df_blog.to_excel('blog_list_naver.xlsx')
# print("네이버 블로그 검색리스트가 엑셀 파일로 저장되었습니다!")

# df_shop.to_excel('shopping_list_naver.xlsx', index=False)
# print("네이버 쇼핑리스트(최저가순) 엑셀 파일로 저장되었습니다!")

--- 쇼핑 검색 결과 ---
                                               title lprice mallName
0  투명 클립 집게 1호 2호 <b>모니터</b> 서류 문서 <b>사무용</b> 종이 ...    190       옥션
1  투명 클립 집게 1호 2호 <b>모니터</b> 서류 문서 <b>사무용</b> 종이 ...    190     밤지마켓
2  투명 클립 집게 1호 2호 <b>모니터</b> 서류 문서 <b>사무용</b> 종이 ...    190      네이버
3  스틸 불독 집게 책 <b>사무용</b> 페이퍼 클립 서류 종이 문구 크립 <b>모니...    260      네이버
4  스틸 불독 집게 책 <b>사무용</b> 페이퍼 클립 서류 종이 문구 크립 <b>모니...    260      리체아

,title,link,image,lprice,hprice,mallName,productId,productType,brand,maker,category1,category2,category3,category4
0,투명 클립 집게 1호 2호 모니터 서류 문서 사무용 종이 메모 책고정집게 집개 클립 핀,https://link.auction.co.kr/gate/pcs?item-no=C9...,https://shopping-phinf.pstatic.net/main_539095...,190,,옥션,53909555081,3,,,생활/건강,문구/사무용품,문구용품,클립/핀
1,투명 클립 집게 1호 2호 모니터 서류 문서 사무용 종이 메모 책고정집게 집개 클립 핀,https://smartstore.naver.com/main/products/790...,https://shopping-phinf.pstatic.net/main_854465...,190,,밤지마켓,85446527876,3,,,생활/건강,문구/사무용품,문구용품,클립/핀
2,투명 클립 집게 1호 2호 모니터 서류 문서 사무용 종이 메모 책고정집게 집개 클립 핀,https://search.shopping.naver.com/catalog/3719...,https://shopping-phinf.pstatic.net/main_371999...,190,,네이버,37199991989,1,,,생활/건강,문구/사무용품,문구용품,클립/핀
3,스틸 불독 집게 책 사무용 페이퍼 클립 서류 종이 문구 크립 모니터 문서 악보 파일...,https://search.shopping.naver.com/catalog/4793...,https://shopping-phinf.pstatic.net/main_479344...,260,,네이버,47934448327,1,,,생활/건강,문구/사무용품,문구용품,클립/핀
4,스틸 불독 집게 책 사무용 페이퍼 클립 서류 종이 문구 크립 모니터 문서 악보 파일...,https://smartstore.naver.com/main/products/103...,https://shopping-phinf.pstatic.net/main_878993...,260,,리체아,87899303522,3,,,생활/건강,문구/사무용품,문구용품,클립/핀
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,[FullyJully] 회색 2구 모니터부착 연필꽂이 오피스 회사원 사무용,https://smartstore.naver.com/main/products/828...,https://shopping-phinf.pstatic.net/main_858325...,1240,,풀리줄리샵,85832546742,2,,,생활/건강,주방용품,주방잡화,기타주방잡화
96,사무용 인덱스 접착 메모지 서류 구분 메모잇 메모수첩 모니터메모 미니접착메모지,https://link.gmarket.co.kr/gate/pcs?item-no=46...,https://shopping-phinf.pstatic.net/main_584303...,1250,,G마켓,58430348448,3,,,생활/건강,문구/사무용품,노트/수첩,점착식메모지
97,그레이 모니터 책상 테이블 부착 펜꽂이 직사각형,https://search.shopping.naver.com/catalog/4382...,https://shopping-phinf.pstatic.net/main_438204...,1250,,네이버,43820485216,1,,,생활/건강,문구/사무용품,데스크용품,연필꽂이
98,사무용 인덱스 접착 메모지 서류 구분 메모잇 메모수첩 모니터메모 미니접착메모지,https://search.shopping.naver.com/catalog/5730...,https://shopping-phinf.pstatic.net/main_573027...,1250,,네이버,57302713301,1,,,생활/건강,문구/사무용품,노트/수첩,점착식메모지
99,3M 포스트잇 653-2 노랑 러블리핑크 51x38mm 200매입,https://smartstore.naver.com/main/products/132...,https://shopping-phinf.pstatic.net/main_907762...,1250,,오피스핫딜,90776258905,3,3M,3M,생활/건강,문구/사무용품,노트/수첩,점착식메모지

In [9]:
cols = ['title', 'lprice', 'mallName'] # 1. 뽑고 싶은 명단을 리스트로 만든다.
df_shop[cols]                          # 2. 그 명단을 판다스에 넣는다.

df_shop[['title', 'lprice', 'mallName']] # 그래서 대괄호가 겹치게 됩니다!

                                                title  lprice mallName
0    투명 클립 집게 1호 2호 모니터 서류 문서 사무용 종이 메모 책고정집게 집개 클립 핀     190     밤지마켓
1    투명 클립 집게 1호 2호 모니터 서류 문서 사무용 종이 메모 책고정집게 집개 클립 핀     190       옥션
2    투명 클립 집게 1호 2호 모니터 서류 문서 사무용 종이 메모 책고정집게 집개 클립 핀     190      네이버
3   스틸 불독 집게 책 사무용 페이퍼 클립 서류 종이 문구 크립 모니터 문서 악보 파일...     260      네이버
4   스틸 불독 집게 책 사무용 페이퍼 클립 서류 종이 문구 크립 모니터 문서 악보 파일...     260      리체아
..                                                ...     ...      ...
95          [FullyJully] 회색 2구 모니터부착 연필꽂이 오피스 회사원 사무용    1240    풀리줄리샵
96               3M 포스트잇 653-2 노랑 러블리핑크 51x38mm 200매입    1250    오피스핫딜
97                         그레이 모니터 책상 테이블 부착 펜꽂이 직사각형    1250      네이버
98        사무용 인덱스 접착 메모지 서류 구분 메모잇 메모수첩 모니터메모 미니접착메모지    1250      네이버
99       [셀러허브]그레이 모니터 책상 테이블 부착 펜꽂이 직사각형 (S11547324)    1250     11번가

[100 rows x 3 columns]